### ISSUE TITLE
noConflict setup causing ReferenceError

### ISSUE THREAD

**Issue by jimf** [talyssonoc/backbone-dispatcher#1]
`root` is being referenced inside the factory function for the purposes of capturing `previousDispatcher`, but `root` is not in scope when this is run. From what I can tell though, `noConflict` isn't needed at all, or should be modified, since `Dispatcher` is being defined on `Backbone` itself and not on `root`.

I'd be happy to submit a pull request, but I just wanted to confirm the best course of action.

**Comment by talyssonoc** [comment]
Fixed in #2
